version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules # 这个文件容器它自己的
    command: npm run dev # 覆盖Dockerfile中的指令