version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 2800:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    image: arnosolo/node-app
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
      # - MONGO_USER=root
      # - MONGO_PASSWORD=example
      # - SESSION_SECRET=secret
    command: node index.js
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    restart: always

volumes:
  mongo-db: